<?php

return [
    // Ristorante italiano
    [
        'name' => 'Spaghetti alla Carbonara',
        'ingredients' => 'Spaghetti, Uova, Guanciale, Formaggio Pecorino, Pepe nero',
        'price' => 12.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Pizza Margherita',
        'ingredients' => 'Impasto per pizza, Salsa di pomodoro, Mozzarella, Basilico fresco, Olio d\'oliva',
        'price' => 10.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Lasagne',
        'ingredients' => 'Fogli di lasagna, Carne macinata, Ricotta, Salsa marinara, Parmigiano',
        'price' => 14.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Risotto ai Funghi',
        'ingredients' => 'Riso Arborio, Funghi, Cipolla, Vino bianco, Parmigiano',
        'price' => 15.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Ossobuco alla Milanese',
        'ingredients' => 'Fesa di vitello, Cipolla, Carota, Sedano, Gremolata',
        'price' => 18.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Gnocchi al Pesto',
        'ingredients' => 'Gnocchi, Pesto al basilico, Parmigiano, Pinoli',
        'price' => 13.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Bruschetta',
        'ingredients' => 'Pane italiano, Pomodori, Aglio, Basilico, Olio d\'oliva',
        'price' => 8.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Minestrone',
        'ingredients' => 'Brodo vegetale, Pasta, Fagioli, Pomodori, Verdure',
        'price' => 9.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Tiramisù',
        'ingredients' => 'Savoiardi, Mascarpone, Caffè, Cacao in polvere',
        'price' => 7.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Calzone',
        'ingredients' => 'Impasto per pizza, Ricotta, Mozzarella, Prosciutto, Salsa di pomodoro',
        'price' => 11.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    // Ristorante giapponese
    [
        'name' => 'Sushi assortiti',
        'ingredients' => 'Riso, Pesce crudo (tonno, salmone, gambero), Alga nori, Wasabi, Salsa di soia',
        'price' => 18.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Tempura di Gamberi',
        'ingredients' => 'Gamberi, Impasto per tempura, Verdure, Salsa tempura',
        'price' => 15.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Ramen di Maiale Tonkotsu',
        'ingredients' => 'Brodo di maiale, Spaghetti ramen, Maiale cotto a fuoco lento, Uova sode, Nori',
        'price' => 14.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Sashimi di Salmone',
        'ingredients' => 'Salmone crudo affettato, Wasabi, Salsa di soia, Ravanelli',
        'price' => 16.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Yakitori',
        'ingredients' => 'Spiedini di pollo, Salsa yakitori, Cipolla verde, Sake',
        'price' => 13.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Gyoza',
        'ingredients' => 'Ravioli al vapore, Maiale macinato, Cavolo cinese, Salsa di soia, Aceto di riso',
        'price' => 11.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Unagi Don',
        'ingredients' => 'Anguilla glassata, Riso, Salsa unagi, Sesamo tostato, Alghe',
        'price' => 17.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Sukiyaki',
        'ingredients' => 'Manzo affettato sottilmente, Tofu, Verdure miste, Brodo dashi, Salsa soia dolce',
        'price' => 19.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Okonomiyaki',
        'ingredients' => 'Cavolo, Pancetta, Uova, Salsa okonomiyaki, Maionese, Fiocchi di bonito',
        'price' => 12.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Miso Soup',
        'ingredients' => 'Brodo miso, Tofu, Alga wakame, Cipolla verde, Funghi',
        'price' => 8.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],

    // Ristorante messicano

    [
        'name' => 'Tacos al Pastor',
        'ingredients' => 'Tortillas di mais, Maiale marinato, Cipolla, Ananas, Salsa rossa',
        'price' => 9.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Guacamole',
        'ingredients' => 'Avocado, Cipolla, Pomodoro, Coriandolo, Peperoncino, Lime',
        'price' => 7.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Enchiladas',
        'ingredients' => 'Tortillas di mais, Pollo, Formaggio, Salsa di pomodoro, Panna acida',
        'price' => 11.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Chiles Rellenos',
        'ingredients' => 'Peperoni verdi, Carne macinata, Formaggio, Salsa di pomodoro',
        'price' => 10.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Burrito',
        'ingredients' => 'Tortilla di farina, Riso, Fagioli, Carne di manzo, Formaggio, Salsa',
        'price' => 12.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Tamales',
        'ingredients' => 'Masa, Carne di maiale, Salsa, Foglie di mais',
        'price' => 8.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Quesadilla',
        'ingredients' => 'Tortilla di mais, Formaggio, Peperoncino, Salsa',
        'price' => 6.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Sopes',
        'ingredients' => 'Dischi di mais, Fagioli, Carne tritata, Formaggio, Lattuga, Panna acida',
        'price' => 9.49,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Pozole',
        'ingredients' => 'Mais omosino, Carne di maiale, Radice di hominy, Peperoncino, Cipolla',
        'price' => 13.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Ceviche',
        'ingredients' => 'Pesce fresco, Lime, Cipolla rossa, Peperoncino, Coriandolo',
        'price' => 14.99,
        'resturant_id' => 3,
        'visibility' => true,
    ]
];
