<?php

return [
    [
        'name' => 'Spaghetti alla Carbonara',
        'ingredients' => 'Spaghetti, Uova, Pancetta, Formaggio Pecorino, Pepe nero',
        'price' => 12.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Pizza Margherita',
        'ingredients' => 'Pizza Dough, Salsa di Pomodoro, Mozzarella, Basilico',
        'price' => 10.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Insalata Caesar',
        'ingredients' => 'Lattuga Romana, Crostini, Parmigiano, Salsa Caesar',
        'price' => 8.49,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Risotto ai Funghi',
        'ingredients' => 'Riso Arborio, Funghi Porcini, Cipolla, Brodo, Burro',
        'price' => 14.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Lasagne al Forno',
        'ingredients' => 'Pasta Lasagna, Ragu di Carne, Besciamella, Parmigiano',
        'price' => 15.49,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Pollo al Curry',
        'ingredients' => 'Pollo, Curry, Latte di Cocco, Peperoni, Cipolla',
        'price' => 13.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Sushi Misto',
        'ingredients' => 'Riso, Salmone, Tonno, Avocado, Alga Nori',
        'price' => 18.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Sushi Misto',
        'ingredients' => 'Riso, Salmone, Tonno, Avocado, Alga Nori',
        'price' => 18.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Hamburger Deluxe',
        'ingredients' => 'Carne di Manzo, Formaggio Cheddar, Lattuga, Pomodoro',
        'price' => 11.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Hamburger Perpoverix',
        'ingredients' => 'Carne di Manzo, Formaggio, Lattuga, Pomodoro',
        'price' => 9.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Insalata Caprese',
        'ingredients' => 'Pomodori, Mozzarella, Basilico, Olio d\'Oliva',
        'price' => 9.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Tagliatelle al Tartufo',
        'ingredients' => 'Tagliatelle, Tartufo Nero, Panna, Parmigiano',
        'price' => 19.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Gnocchi al Pesto',
        'ingredients' => 'Gnocchi, Pesto, Pinoli, Parmigiano',
        'price' => 12.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Tacos di Pollo',
        'ingredients' => 'Tortillas, Pollo, Salsa di Pomodoro, Lattuga, Formaggio',
        'price' => 10.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    // Puoi continuare ad aggiungere altri piatti qui...
];
