<?php

return [
    // Ristorante italiano
    [
        'name' => 'Spaghetti alla Carbonara',
        'ingredients' => 'Spaghetti, Uova, Guanciale, Formaggio Pecorino, Pepe nero',
        'price' => 12.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Pizza Margherita',
        'ingredients' => 'Impasto per pizza, Salsa di pomodoro, Mozzarella, Basilico fresco, Olio d\'oliva',
        'price' => 10.99,
        'resturant_id' => 1,
        'visibility' => false,
    ],
    [
        'name' => 'Lasagne',
        'ingredients' => 'Fogli di lasagna, Carne macinata, Ricotta, Salsa marinara, Parmigiano',
        'price' => 14.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Risotto ai Funghi',
        'ingredients' => 'Riso Arborio, Funghi, Cipolla, Vino bianco, Parmigiano',
        'price' => 15.99,
        'resturant_id' => 1,
        'visibility' => false,
    ],
    [
        'name' => 'Ossobuco alla Milanese',
        'ingredients' => 'Fesa di vitello, Cipolla, Carota, Sedano, Gremolata',
        'price' => 18.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Gnocchi al Pesto',
        'ingredients' => 'Gnocchi, Pesto al basilico, Parmigiano, Pinoli',
        'price' => 13.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Bruschetta',
        'ingredients' => 'Pane italiano, Pomodori, Aglio, Basilico, Olio d\'oliva',
        'price' => 8.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Minestrone',
        'ingredients' => 'Brodo vegetale, Pasta, Fagioli, Pomodori, Verdure',
        'price' => 9.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Tiramisù',
        'ingredients' => 'Savoiardi, Mascarpone, Caffè, Cacao in polvere',
        'price' => 7.99,
        'resturant_id' => 1,
        'visibility' => true,
    ],
    [
        'name' => 'Calzone',
        'ingredients' => 'Impasto per pizza, Ricotta, Mozzarella, Prosciutto, Salsa di pomodoro',
        'price' => 11.99,
        'resturant_id' => 1,
        'visibility' => false,
    ],
    // Ristorante giapponese
    [
        'name' => 'Sushi assortiti',
        'ingredients' => 'Riso, Pesce crudo (tonno, salmone, gambero), Alga nori, Wasabi, Salsa di soia',
        'price' => 18.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Tempura di Gamberi',
        'ingredients' => 'Gamberi, Impasto per tempura, Verdure, Salsa tempura',
        'price' => 15.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Ramen di Maiale Tonkotsu',
        'ingredients' => 'Brodo di maiale, Spaghetti ramen, Maiale cotto a fuoco lento, Uova sode, Nori',
        'price' => 14.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Sashimi di Salmone',
        'ingredients' => 'Salmone crudo affettato, Wasabi, Salsa di soia, Ravanelli',
        'price' => 16.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Yakitori',
        'ingredients' => 'Spiedini di pollo, Salsa yakitori, Cipolla verde, Sake',
        'price' => 13.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Gyoza',
        'ingredients' => 'Ravioli al vapore, Maiale macinato, Cavolo cinese, Salsa di soia, Aceto di riso',
        'price' => 11.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Unagi Don',
        'ingredients' => 'Anguilla glassata, Riso, Salsa unagi, Sesamo tostato, Alghe',
        'price' => 17.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Sukiyaki',
        'ingredients' => 'Manzo affettato sottilmente, Tofu, Verdure miste, Brodo dashi, Salsa soia dolce',
        'price' => 19.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Okonomiyaki',
        'ingredients' => 'Cavolo, Pancetta, Uova, Salsa okonomiyaki, Maionese, Fiocchi di bonito',
        'price' => 12.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],
    [
        'name' => 'Miso Soup',
        'ingredients' => 'Brodo miso, Tofu, Alga wakame, Cipolla verde, Funghi',
        'price' => 8.99,
        'resturant_id' => 2,
        'visibility' => true,
    ],

    // Ristorante messicano

    [
        'name' => 'Tacos al Pastor',
        'ingredients' => 'Tortillas di mais, Maiale marinato, Cipolla, Ananas, Salsa rossa',
        'price' => 9.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Guacamole',
        'ingredients' => 'Avocado, Cipolla, Pomodoro, Coriandolo, Peperoncino, Lime',
        'price' => 7.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Enchiladas',
        'ingredients' => 'Tortillas di mais, Pollo, Formaggio, Salsa di pomodoro, Panna acida',
        'price' => 11.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Chiles Rellenos',
        'ingredients' => 'Peperoni verdi, Carne macinata, Formaggio, Salsa di pomodoro',
        'price' => 10.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Burrito',
        'ingredients' => 'Tortilla di farina, Riso, Fagioli, Carne di manzo, Formaggio, Salsa',
        'price' => 12.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Tamales',
        'ingredients' => 'Masa, Carne di maiale, Salsa, Foglie di mais',
        'price' => 8.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Quesadilla',
        'ingredients' => 'Tortilla di mais, Formaggio, Peperoncino, Salsa',
        'price' => 6.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Sopes',
        'ingredients' => 'Dischi di mais, Fagioli, Carne tritata, Formaggio, Lattuga, Panna acida',
        'price' => 9.49,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Pozole',
        'ingredients' => 'Mais omosino, Carne di maiale, Radice di hominy, Peperoncino, Cipolla',
        'price' => 13.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    [
        'name' => 'Ceviche',
        'ingredients' => 'Pesce fresco, Lime, Cipolla rossa, Peperoncino, Coriandolo',
        'price' => 14.99,
        'resturant_id' => 3,
        'visibility' => true,
    ],
    //Ristorante greco di Maria
    [
        'name' => 'Moussaka',
        'ingredients' => 'Melanzane, Carne di manzo macinata, Bechamel, Formaggio, Pomodoro',
        'price' => 14.99,
        'resturant_id' => 4,
        'visibility' => true,
    ],
    [
        'name' => 'Souvlaki',
        'ingredients' => 'Spiedini di carne (agnello o maiale), Cipolla, Pomodoro, Tzatziki',
        'price' => 12.99,
        'resturant_id' => 4,
        'visibility' => true,
    ],
    [
        'name' => 'Spanakopita',
        'ingredients' => 'Spinaci, Formaggio feta, Cipolla, Pasta fillo',
        'price' => 10.99,
        'resturant_id' => 4,
        'visibility' => true,
    ],
    [
        'name' => 'Dolmades',
        'ingredients' => 'Foglie di vite ripiene di riso e carne',
        'price' => 9.99,
        'resturant_id' => 4,
        'visibility' => true,
    ],
    [
        'name' => 'Horiatiki Salata',
        'ingredients' => 'Insalata greca con pomodori, cetrioli, olive, feta e olio d\'oliva',
        'price' => 8.99,
        'resturant_id' => 4,
        'visibility' => true,
    ],
    [
        'name' => 'Baklava',
        'ingredients' => 'Dolce a base di pasta fillo, noci, miele e cannella',
        'price' => 7.99,
        'resturant_id' => 4,
        'visibility' => true,
    ],
    [
        'name' => 'Retsina',
        'ingredients' => 'Vino greco aromatizzato alla resina di pino',
        'price' => 5.99,
        'resturant_id' => 4,
        'visibility' => true,
    ],
    [
        'name' => 'Galaktoboureko',
        'ingredients' => 'Dolce al semolino con sciroppo',
        'price' => 8.99,
        'resturant_id' => 4,
        'visibility' => true,
    ],
    [
        'name' => 'Kleftiko',
        'ingredients' => 'Agnello cotto lentamente con erbe e limone',
        'price' => 16.99,
        'resturant_id' => 4,
        'visibility' => true,
    ],
    [
        'name' => 'Frappe',
        'ingredients' => 'Caffè freddo schiumato',
        'price' => 4.99,
        'resturant_id' => 4,
        'visibility' => true,
    ],

    // Piatti per Sapori d'India Ristorante
    [
        'name' => 'Chicken Tikka Masala',
        'ingredients' => 'Pollo, Salsa di pomodoro, Yogurt, Spezie indiane',
        'price' => 13.99,
        'resturant_id' => 5,
        'visibility' => true,
    ],
    [
        'name' => 'Naan',
        'ingredients' => 'Pane indiano cotto al forno tandoor',
        'price' => 3.99,
        'resturant_id' => 5,
        'visibility' => true,
    ],
    [
        'name' => 'Palak Paneer',
        'ingredients' => 'Spinaci, Formaggio paneer, Spezie',
        'price' => 11.99,
        'resturant_id' => 5,
        'visibility' => true,
    ],
    [
        'name' => 'Biryani di Agnello',
        'ingredients' => 'Riso, Agnello, Spezie, Yogurt, Cipolla fritta',
        'price' => 15.99,
        'resturant_id' => 5,
        'visibility' => true,
    ],
    [
        'name' => 'Samosa',
        'ingredients' => 'Triangoli di pasta ripieni di patate e piselli',
        'price' => 4.99,
        'resturant_id' => 5,
        'visibility' => true,
    ],
    [
        'name' => 'Mango Lassi',
        'ingredients' => 'Bevanda a base di yogurt e mango',
        'price' => 3.99,
        'resturant_id' => 5,
        'visibility' => true,
    ],
    [
        'name' => 'Raita',
        'ingredients' => 'Yogurt con cetrioli e spezie',
        'price' => 3.49,
        'resturant_id' => 5,
        'visibility' => true,
    ],
    [
        'name' => 'Aloo Gobi',
        'ingredients' => 'Patate, Cavolfiore, Spezie',
        'price' => 10.99,
        'resturant_id' => 5,
        'visibility' => true,
    ],
    [
        'name' => 'Paneer Tikka',
        'ingredients' => 'Formaggio paneer marinato e grigliato',
        'price' => 9.99,
        'resturant_id' => 5,
        'visibility' => true,
    ],
    [
        'name' => 'Gulab Jamun',
        'ingredients' => 'Palle dolci fritte in sciroppo',
        'price' => 5.99,
        'resturant_id' => 5,
        'visibility' => true,
    ],
    // Piatti per Le Bistro Ristorante
    [
        'name' => 'Coq au Vin',
        'ingredients' => 'Pollo, Vino rosso, Funghi, Cipolla, Pancetta',
        'price' => 16.99,
        'resturant_id' => 6,
        'visibility' => true,
    ],
    [
        'name' => 'Ratatouille',
        'ingredients' => 'Verdure miste, Pomodori, Erbe aromatiche',
        'price' => 12.99,
        'resturant_id' => 6,
        'visibility' => true,
    ],
    [
        'name' => 'Escargot',
        'ingredients' => 'Chiocciole in salsa di burro all\'aglio e prezzemolo',
        'price' => 14.99,
        'resturant_id' => 6,
        'visibility' => true,
    ],
    [
        'name' => 'Bouillabaisse',
        'ingredients' => 'Zuppa di pesce con varietà di pesci e crostacei',
        'price' => 18.99,
        'resturant_id' => 6,
        'visibility' => true,
    ],
    [
        'name' => 'Crème Brûlée',
        'ingredients' => 'Custard con crosta caramellata',
        'price' => 8.99,
        'resturant_id' => 6,
        'visibility' => true,
    ],
    [
        'name' => 'Quiche Lorraine',
        'ingredients' => 'Uova, Pancetta, Formaggio, Panna',
        'price' => 10.99,
        'resturant_id' => 6,
        'visibility' => true,
    ],
    [
        'name' => 'Salade Niçoise',
        'ingredients' => 'Insalata, Tonno, Uova sode, Pomodori, Olive, Fagiolini',
        'price' => 12.99,
        'resturant_id' => 6,
        'visibility' => true,
    ],
    [
        'name' => 'Tarte Tatin',
        'ingredients' => 'Torta di mele caramellata',
        'price' => 9.99,
        'resturant_id' => 6,
        'visibility' => true,
    ],
    [
        'name' => 'Croissant',
        'ingredients' => 'Pane dolce a base di burro',
        'price' => 3.99,
        'resturant_id' => 6,
        'visibility' => true,
    ],
    [
        'name' => 'Champagne',
        'ingredients' => 'Vino spumante francese',
        'price' => 45.99,
        'resturant_id' => 6,
        'visibility' => true,
    ],

    // Piatti per Trattoria Maria
    [
        'name' => 'Margherita Pizza',
        'ingredients' => 'Impasto per pizza, Salsa di pomodoro, Mozzarella, Basilico',
        'price' => 10.99,
        'resturant_id' => 7,
        'visibility' => true,
    ],
    [
        'name' => 'Penne alla Vodka',
        'ingredients' => 'Penne, Salsa di pomodoro alla vodka, Pancetta, Panna',
        'price' => 12.99,
        'resturant_id' => 7,
        'visibility' => true,
    ],
    [
        'name' => 'Tortellini Alfredo',
        'ingredients' => 'Tortellini, Salsa Alfredo, Piselli, Prosciutto',
        'price' => 13.99,
        'resturant_id' => 7,
        'visibility' => true,
    ],
    [
        'name' => 'Osso Buco',
        'ingredients' => 'Fesa di vitello, Soffritto, Vino bianco, Brodo di carne',
        'price' => 17.99,
        'resturant_id' => 7,
        'visibility' => true,
    ],
    [
        'name' => 'Cannoli Siciliani',
        'ingredients' => 'Cialde di ricotta, Cioccolato, Canditi',
        'price' => 7.99,
        'resturant_id' => 7,
        'visibility' => true,
    ],
    [
        'name' => 'Frittura di Calamari',
        'ingredients' => 'Calamari fritti, Limone, Salsa marinara',
        'price' => 11.99,
        'resturant_id' => 7,
        'visibility' => true,
    ],
    [
        'name' => 'Insalata Caprese',
        'ingredients' => 'Pomodori, Mozzarella, Basilico, Olio d\'oliva',
        'price' => 8.99,
        'resturant_id' => 7,
        'visibility' => true,
    ],
    [
        'name' => 'Panna Cotta',
        'ingredients' => 'Dolce cremoso, Caramello',
        'price' => 6.99,
        'resturant_id' => 7,
        'visibility' => true,
    ],
    [
        'name' => 'Limoncello',
        'ingredients' => 'Liquore al limone',
        'price' => 5.99,
        'resturant_id' => 7,
        'visibility' => true,
    ],
    [
        'name' => 'Espresso',
        'ingredients' => 'Caffè espresso italiano',
        'price' => 2.99,
        'resturant_id' => 7,
        'visibility' => true,
    ],

    // Piatti per Sushi Express
    [
        'name' => 'Sashimi Misto',
        'ingredients' => 'Selezione di sashimi misti',
        'price' => 19.99,
        'resturant_id' => 8,
        'visibility' => true,
    ],
    [
        'name' => 'Tempura di Verdure',
        'ingredients' => 'Verdure in pastella fritte, Salsa tempura',
        'price' => 11.99,
        'resturant_id' => 8,
        'visibility' => true,
    ],
    [
        'name' => 'Uramaki Sushi',
        'ingredients' => 'Sushi al contrario con gambero, avocado, maionese',
        'price' => 15.99,
        'resturant_id' => 8,
        'visibility' => true,
    ],
    [
        'name' => 'Nigiri Sushi',
        'ingredients' => 'Selezione di nigiri sushi',
        'price' => 17.99,
        'resturant_id' => 8,
        'visibility' => true,
    ],
    [
        'name' => 'Mochi Dolci',
        'ingredients' => 'Dolci giapponesi di riso glutinoso',
        'price' => 8.99,
        'resturant_id' => 8,
        'visibility' => true,
    ],
    [
        'name' => 'Goma Wakame',
        'ingredients' => 'Insalata di alghe in salsa di sesamo',
        'price' => 6.99,
        'resturant_id' => 8,
        'visibility' => true,
    ],
    [
        'name' => 'Sake',
        'ingredients' => 'Sake giapponese',
        'price' => 14.99,
        'resturant_id' => 8,
        'visibility' => true,
    ],
    [
        'name' => 'Matcha Latte',
        'ingredients' => 'Latte al tè matcha',
        'price' => 4.99,
        'resturant_id' => 8,
        'visibility' => true,
    ],
    [
        'name' => 'Yuzu Sorbetto',
        'ingredients' => 'Sorbetto al gusto di yuzu',
        'price' => 5.99,
        'resturant_id' => 8,
        'visibility' => true,
    ],
    [
        'name' => 'Miso Shiru',
        'ingredients' => 'Zuppa di miso',
        'price' => 3.99,
        'resturant_id' => 8,
        'visibility' => true,
    ],

    // Piatti per Taqueria Mexico
    [
        'name' => 'Tacos al Carnitas',
        'ingredients' => 'Tortillas di mais, Carne di maiale stufata, Cipolla, Coriandolo',
        'price' => 9.99,
        'resturant_id' => 9,
        'visibility' => true,
    ],
    [
        'name' => 'Chiles en Nogada',
        'ingredients' => 'Peperoni verdi ripieni di carne di manzo, salsa di noci e melograno',
        'price' => 12.99,
        'resturant_id' => 9,
        'visibility' => true,
    ],
    [
        'name' => 'Mole Poblano',
        'ingredients' => 'Pollo in salsa di mole poblano con cioccolato e spezie',
        'price' => 13.99,
        'resturant_id' => 9,
        'visibility' => true,
    ],
    [
        'name' => 'Tamales Verdes',
        'ingredients' => 'Tamales di mais con salsa verde e carne di pollo',
        'price' => 10.99,
        'resturant_id' => 9,
        'visibility' => true,
    ],
    [
        'name' => 'Sopes al Pastor',
        'ingredients' => 'Dischi di mais, Maiale al pastor, Salsa rossa, Lattuga, Formaggio',
        'price' => 11.99,
        'resturant_id' => 9,
        'visibility' => true,
    ],
    [
        'name' => 'Camarones a la Diabla',
        'ingredients' => 'Gamberi in salsa di pomodoro piccante',
        'price' => 15.99,
        'resturant_id' => 9,
        'visibility' => true,
    ],
    [
        'name' => 'Guacamole',
        'ingredients' => 'Avocado, Cipolla, Pomodoro, Coriandolo, Peperoncino, Lime',
        'price' => 7.99,
        'resturant_id' => 9,
        'visibility' => true,
    ],
    [
        'name' => 'Tres Leches Cake',
        'ingredients' => 'Torta tre latte con panna montata',
        'price' => 6.99,
        'resturant_id' => 9,
        'visibility' => true,
    ],
    [
        'name' => 'Horchata',
        'ingredients' => 'Bevanda di riso aromatizzata alla cannella',
        'price' => 3.99,
        'resturant_id' => 9,
        'visibility' => true,
    ],
    [
        'name' => 'Margarita',
        'ingredients' => 'Cocktail di tequila e lime',
        'price' => 8.99,
        'resturant_id' => 9,
        'visibility' => true,
    ],

    // Piatti per Greek Delights
    [
        'name' => 'Souvlaki',
        'ingredients' => 'Spiedini di carne di maiale marinati',
        'price' => 10.99,
        'resturant_id' => 10,
        'visibility' => true,
    ],
    [
        'name' => 'Moussaka',
        'ingredients' => 'Parmigiana greca con melanzane, carne macinata, besciamella',
        'price' => 12.99,
        'resturant_id' => 10,
        'visibility' => true,
    ],
    [
        'name' => 'Tzatziki',
        'ingredients' => 'Salsa di yogurt con cetrioli e aglio',
        'price' => 5.99,
        'resturant_id' => 10,
        'visibility' => true,
    ],
    [
        'name' => 'Greek Salad',
        'ingredients' => 'Insalata greca con pomodori, cetrioli, olive, feta',
        'price' => 8.99,
        'resturant_id' => 10,
        'visibility' => true,
    ],
    [
        'name' => 'Dolmades',
        'ingredients' => 'Foglie di vite ripiene di riso e carne',
        'price' => 9.99,
        'resturant_id' => 10,
        'visibility' => true,
    ],
    [
        'name' => 'Spanakopita',
        'ingredients' => 'Pasticcio di spinaci e formaggio feta in pasta fillo',
        'price' => 11.99,
        'resturant_id' => 10,
        'visibility' => true,
    ],
    [
        'name' => 'Baklava',
        'ingredients' => 'Dolce greco a strati con noci e miele',
        'price' => 7.99,
        'resturant_id' => 10,
        'visibility' => true,
    ],
    [
        'name' => 'Ouzo',
        'ingredients' => 'Liquore greco all\'anice',
        'price' => 6.99,
        'resturant_id' => 10,
        'visibility' => true,
    ],
    [
        'name' => 'Greek Coffee',
        'ingredients' => 'Caffè greco tradizionale',
        'price' => 3.99,
        'resturant_id' => 10,
        'visibility' => true,
    ],
    [
        'name' => 'Retsina',
        'ingredients' => 'Vino greco al pino',
        'price' => 12.99,
        'resturant_id' => 10,
        'visibility' => true,
    ],
];